/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_IRenderWindow */

#ifndef _Included_org_ogre4j_IRenderWindow
#define _Included_org_ogre4j_IRenderWindow
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
