/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Root */

#ifndef _Included_org_ogre4j_Root
#define _Included_org_ogre4j_Root
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_Root
 * Method:    addFrameListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_addFrameListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    addResourceLocation
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_addResourceLocation
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jboolean);

/*
 * Class:     org_ogre4j_Root
 * Method:    clearEventTimes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_clearEventTimes
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    createCppInstance
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_createCppInstance
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_ogre4j_Root
 * Method:    createRenderWindow
 * Signature: (ILjava/lang/String;IIZLjava/lang/String;IIIZIIIFZ)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_createRenderWindow
  (JNIEnv *, jclass, jint, jstring, jint, jint, jboolean, jstring, jint, jint, jint, jboolean, jint, jint, jint, jfloat, jboolean);

/*
 * Class:     org_ogre4j_Root
 * Method:    getAvailableRenderes
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_ogre4j_Root_getAvailableRenderes
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    getErrorDescription
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_Root_getErrorDescription
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_ogre4j_Root
 * Method:    getMeshManager
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_getMeshManager
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    getRenderSystem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_getRenderSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    getSceneManager
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_getSceneManager
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    getSingletonImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_getSingletonImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_Root
 * Method:    getTextureManager
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_getTextureManager
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    initialise
 * Signature: (IZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Root_initialise
  (JNIEnv *, jclass, jint, jboolean, jstring);

/*
 * Class:     org_ogre4j_Root
 * Method:    loadPlugin
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_loadPlugin
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_Root
 * Method:    queueEndRendering
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_queueEndRendering
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    removeFrameListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_removeFrameListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    renderOneFrame
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_Root_renderOneFrame
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    setRenderSystem
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_setRenderSystem
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    showConfigDialog
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_Root_showConfigDialog
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    shutdown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_shutdown
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    startRendering
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_startRendering
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Root
 * Method:    unloadPlugin
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Root_unloadPlugin
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
