/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_StringInterface */

#ifndef _Included_org_ogre4j_StringInterface
#define _Included_org_ogre4j_StringInterface
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_StringInterface
 * Method:    copyParametersTo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_StringInterface_copyParametersTo
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_StringInterface
 * Method:    getParamDictionary
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_StringInterface_getParamDictionary
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_StringInterface
 * Method:    getParameter
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_StringInterface_getParameter
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_StringInterface
 * Method:    getParameters
 * Signature: (I)[Lorg/ogre4j/ParameterDef;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ogre4j_StringInterface_getParameters
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_StringInterface
 * Method:    setParameter
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_StringInterface_setParameter
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_ogre4j_StringInterface
 * Method:    setParameterList
 * Signature: (I[Ljava/lang/Object;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_StringInterface_setParameterList
  (JNIEnv *, jclass, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
