/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_DefaultHardwareBufferManager */

#ifndef _Included_org_ogre4j_DefaultHardwareBufferManager
#define _Included_org_ogre4j_DefaultHardwareBufferManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: pInstance */
/* Inaccessible static: singleton */
/*
 * Class:     org_ogre4j_DefaultHardwareBufferManager
 * Method:    createInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_DefaultHardwareBufferManager_createInstance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
