/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_SubEntity */

#ifndef _Included_org_ogre4j_SubEntity
#define _Included_org_ogre4j_SubEntity
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_SubEntity
 * Method:    getMaterialName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_SubEntity_getMaterialName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_SubEntity
 * Method:    isVisible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_SubEntity_isVisible
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_SubEntity
 * Method:    setMaterialName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_SubEntity_setMaterialName
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
