/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_VertexElement */

#ifndef _Included_org_ogre4j_VertexElement
#define _Included_org_ogre4j_VertexElement
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_VertexElement
 * Method:    getTypeSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_VertexElement_getTypeSize
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
