/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Helper */

#ifndef _Included_org_ogre4j_Helper
#define _Included_org_ogre4j_Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ogre4j_Helper
 * Method:    _getDirectXVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_Helper__1getDirectXVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
