/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_NativeObject */

#ifndef _Included_org_ogre4j_NativeObject
#define _Included_org_ogre4j_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_NativeObject
 * Method:    getT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_NativeObject_getT
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
