/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_MeshSerializer */

#ifndef _Included_org_ogre4j_MeshSerializer
#define _Included_org_ogre4j_MeshSerializer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_MeshSerializer
 * Method:    createInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_MeshSerializer_createInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_MeshSerializer
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MeshSerializer_dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_MeshSerializer
 * Method:    exportMesh
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MeshSerializer_exportMesh
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
