/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Win32Window */

#ifndef _Included_org_ogre4j_Win32Window
#define _Included_org_ogre4j_Win32Window
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_Win32Window
 * Method:    create
 * Signature: (ILjava/lang/String;IIZLjava/lang/String;IIIZIIIFZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Win32Window_create
  (JNIEnv *, jclass, jint, jstring, jint, jint, jboolean, jstring, jint, jint, jint, jboolean, jint, jint, jint, jfloat, jboolean);

/*
 * Class:     org_ogre4j_Win32Window
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Win32Window_destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Win32Window
 * Method:    resize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Win32Window_resize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_ogre4j_Win32Window
 * Method:    reposition
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Win32Window_reposition
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_ogre4j_Win32Window
 * Method:    isClosed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_Win32Window_isClosed
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Win32Window
 * Method:    swapBuffers
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Win32Window_swapBuffers
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ogre4j_Win32Window
 * Method:    requiresTextureFlipping
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_Win32Window_requiresTextureFlipping
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
