/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_ResourceManager */

#ifndef _Included_org_ogre4j_ResourceManager
#define _Included_org_ogre4j_ResourceManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_ResourceManager
 * Method:    getMemoryBudget
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_ResourceManager_getMemoryBudget
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_ResourceManager
 * Method:    remove
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceManager_remove
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_ResourceManager
 * Method:    removeAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceManager_removeAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_ResourceManager
 * Method:    setMemoryBudget
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceManager_setMemoryBudget
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_ogre4j_ResourceManager
 * Method:    unloadAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceManager_unloadAll
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
