/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_ParameterDef */

#ifndef _Included_org_ogre4j_ParameterDef
#define _Included_org_ogre4j_ParameterDef
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ogre4j_ParameterDef_PT_BOOL
#define org_ogre4j_ParameterDef_PT_BOOL 0L
#undef org_ogre4j_ParameterDef_PT_COLOURVALUE
#define org_ogre4j_ParameterDef_PT_COLOURVALUE 13L
#undef org_ogre4j_ParameterDef_PT_INT
#define org_ogre4j_ParameterDef_PT_INT 2L
#undef org_ogre4j_ParameterDef_PT_LONG
#define org_ogre4j_ParameterDef_PT_LONG 6L
#undef org_ogre4j_ParameterDef_PT_MATRIX3
#define org_ogre4j_ParameterDef_PT_MATRIX3 10L
#undef org_ogre4j_ParameterDef_PT_MATRIX4
#define org_ogre4j_ParameterDef_PT_MATRIX4 11L
#undef org_ogre4j_ParameterDef_PT_QUATERNION
#define org_ogre4j_ParameterDef_PT_QUATERNION 12L
#undef org_ogre4j_ParameterDef_PT_REAL
#define org_ogre4j_ParameterDef_PT_REAL 1L
#undef org_ogre4j_ParameterDef_PT_SHORT
#define org_ogre4j_ParameterDef_PT_SHORT 4L
#undef org_ogre4j_ParameterDef_PT_STRING
#define org_ogre4j_ParameterDef_PT_STRING 8L
#undef org_ogre4j_ParameterDef_PT_UNSIGNED_INT
#define org_ogre4j_ParameterDef_PT_UNSIGNED_INT 3L
#undef org_ogre4j_ParameterDef_PT_UNSIGNED_LONG
#define org_ogre4j_ParameterDef_PT_UNSIGNED_LONG 7L
#undef org_ogre4j_ParameterDef_PT_UNSIGNED_SHORT
#define org_ogre4j_ParameterDef_PT_UNSIGNED_SHORT 5L
#undef org_ogre4j_ParameterDef_PT_VECTOR3
#define org_ogre4j_ParameterDef_PT_VECTOR3 9L
/*
 * Class:     org_ogre4j_ParameterDef
 * Method:    ctor
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ParameterDef_ctor
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
