/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_MouseMotionTargetImpl */

#ifndef _Included_org_ogre4j_MouseMotionTargetImpl
#define _Included_org_ogre4j_MouseMotionTargetImpl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_MouseMotionTargetImpl
 * Method:    addMouseMotionListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MouseMotionTargetImpl_addMouseMotionListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_MouseMotionTargetImpl
 * Method:    removeMouseMotionListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MouseMotionTargetImpl_removeMouseMotionListener
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
