/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_InputReader */

#ifndef _Included_org_ogre4j_InputReader
#define _Included_org_ogre4j_InputReader
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
#undef org_ogre4j_InputReader_KC_ESCAPE
#define org_ogre4j_InputReader_KC_ESCAPE 1L
#undef org_ogre4j_InputReader_KC_1
#define org_ogre4j_InputReader_KC_1 2L
#undef org_ogre4j_InputReader_KC_2
#define org_ogre4j_InputReader_KC_2 3L
#undef org_ogre4j_InputReader_KC_3
#define org_ogre4j_InputReader_KC_3 4L
#undef org_ogre4j_InputReader_KC_4
#define org_ogre4j_InputReader_KC_4 5L
#undef org_ogre4j_InputReader_KC_5
#define org_ogre4j_InputReader_KC_5 6L
#undef org_ogre4j_InputReader_KC_6
#define org_ogre4j_InputReader_KC_6 7L
#undef org_ogre4j_InputReader_KC_7
#define org_ogre4j_InputReader_KC_7 8L
#undef org_ogre4j_InputReader_KC_8
#define org_ogre4j_InputReader_KC_8 9L
#undef org_ogre4j_InputReader_KC_9
#define org_ogre4j_InputReader_KC_9 10L
#undef org_ogre4j_InputReader_KC_0
#define org_ogre4j_InputReader_KC_0 11L
#undef org_ogre4j_InputReader_KC_MINUS
#define org_ogre4j_InputReader_KC_MINUS 12L
#undef org_ogre4j_InputReader_KC_EQUALS
#define org_ogre4j_InputReader_KC_EQUALS 13L
#undef org_ogre4j_InputReader_KC_BACK
#define org_ogre4j_InputReader_KC_BACK 14L
#undef org_ogre4j_InputReader_KC_TAB
#define org_ogre4j_InputReader_KC_TAB 15L
#undef org_ogre4j_InputReader_KC_Q
#define org_ogre4j_InputReader_KC_Q 16L
#undef org_ogre4j_InputReader_KC_W
#define org_ogre4j_InputReader_KC_W 17L
#undef org_ogre4j_InputReader_KC_E
#define org_ogre4j_InputReader_KC_E 18L
#undef org_ogre4j_InputReader_KC_R
#define org_ogre4j_InputReader_KC_R 19L
#undef org_ogre4j_InputReader_KC_T
#define org_ogre4j_InputReader_KC_T 20L
#undef org_ogre4j_InputReader_KC_Y
#define org_ogre4j_InputReader_KC_Y 21L
#undef org_ogre4j_InputReader_KC_U
#define org_ogre4j_InputReader_KC_U 22L
#undef org_ogre4j_InputReader_KC_I
#define org_ogre4j_InputReader_KC_I 23L
#undef org_ogre4j_InputReader_KC_O
#define org_ogre4j_InputReader_KC_O 24L
#undef org_ogre4j_InputReader_KC_P
#define org_ogre4j_InputReader_KC_P 25L
#undef org_ogre4j_InputReader_KC_LBRACKET
#define org_ogre4j_InputReader_KC_LBRACKET 26L
#undef org_ogre4j_InputReader_KC_RBRACKET
#define org_ogre4j_InputReader_KC_RBRACKET 27L
#undef org_ogre4j_InputReader_KC_RETURN
#define org_ogre4j_InputReader_KC_RETURN 28L
#undef org_ogre4j_InputReader_KC_LCONTROL
#define org_ogre4j_InputReader_KC_LCONTROL 29L
#undef org_ogre4j_InputReader_KC_A
#define org_ogre4j_InputReader_KC_A 30L
#undef org_ogre4j_InputReader_KC_S
#define org_ogre4j_InputReader_KC_S 31L
#undef org_ogre4j_InputReader_KC_D
#define org_ogre4j_InputReader_KC_D 32L
#undef org_ogre4j_InputReader_KC_F
#define org_ogre4j_InputReader_KC_F 33L
#undef org_ogre4j_InputReader_KC_G
#define org_ogre4j_InputReader_KC_G 34L
#undef org_ogre4j_InputReader_KC_H
#define org_ogre4j_InputReader_KC_H 35L
#undef org_ogre4j_InputReader_KC_J
#define org_ogre4j_InputReader_KC_J 36L
#undef org_ogre4j_InputReader_KC_K
#define org_ogre4j_InputReader_KC_K 37L
#undef org_ogre4j_InputReader_KC_L
#define org_ogre4j_InputReader_KC_L 38L
#undef org_ogre4j_InputReader_KC_SEMICOLON
#define org_ogre4j_InputReader_KC_SEMICOLON 39L
#undef org_ogre4j_InputReader_KC_APOSTROPHE
#define org_ogre4j_InputReader_KC_APOSTROPHE 40L
#undef org_ogre4j_InputReader_KC_GRAVE
#define org_ogre4j_InputReader_KC_GRAVE 41L
#undef org_ogre4j_InputReader_KC_LSHIFT
#define org_ogre4j_InputReader_KC_LSHIFT 42L
#undef org_ogre4j_InputReader_KC_BACKSLASH
#define org_ogre4j_InputReader_KC_BACKSLASH 43L
#undef org_ogre4j_InputReader_KC_Z
#define org_ogre4j_InputReader_KC_Z 44L
#undef org_ogre4j_InputReader_KC_X
#define org_ogre4j_InputReader_KC_X 45L
#undef org_ogre4j_InputReader_KC_C
#define org_ogre4j_InputReader_KC_C 46L
#undef org_ogre4j_InputReader_KC_V
#define org_ogre4j_InputReader_KC_V 47L
#undef org_ogre4j_InputReader_KC_B
#define org_ogre4j_InputReader_KC_B 48L
#undef org_ogre4j_InputReader_KC_N
#define org_ogre4j_InputReader_KC_N 49L
#undef org_ogre4j_InputReader_KC_M
#define org_ogre4j_InputReader_KC_M 50L
#undef org_ogre4j_InputReader_KC_COMMA
#define org_ogre4j_InputReader_KC_COMMA 51L
#undef org_ogre4j_InputReader_KC_PERIOD
#define org_ogre4j_InputReader_KC_PERIOD 52L
#undef org_ogre4j_InputReader_KC_SLASH
#define org_ogre4j_InputReader_KC_SLASH 53L
#undef org_ogre4j_InputReader_KC_RSHIFT
#define org_ogre4j_InputReader_KC_RSHIFT 54L
#undef org_ogre4j_InputReader_KC_MULTIPLY
#define org_ogre4j_InputReader_KC_MULTIPLY 55L
#undef org_ogre4j_InputReader_KC_LMENU
#define org_ogre4j_InputReader_KC_LMENU 56L
#undef org_ogre4j_InputReader_KC_SPACE
#define org_ogre4j_InputReader_KC_SPACE 57L
#undef org_ogre4j_InputReader_KC_CAPITAL
#define org_ogre4j_InputReader_KC_CAPITAL 58L
#undef org_ogre4j_InputReader_KC_F1
#define org_ogre4j_InputReader_KC_F1 59L
#undef org_ogre4j_InputReader_KC_F2
#define org_ogre4j_InputReader_KC_F2 60L
#undef org_ogre4j_InputReader_KC_F3
#define org_ogre4j_InputReader_KC_F3 61L
#undef org_ogre4j_InputReader_KC_F4
#define org_ogre4j_InputReader_KC_F4 62L
#undef org_ogre4j_InputReader_KC_F5
#define org_ogre4j_InputReader_KC_F5 63L
#undef org_ogre4j_InputReader_KC_F6
#define org_ogre4j_InputReader_KC_F6 64L
#undef org_ogre4j_InputReader_KC_F7
#define org_ogre4j_InputReader_KC_F7 65L
#undef org_ogre4j_InputReader_KC_F8
#define org_ogre4j_InputReader_KC_F8 66L
#undef org_ogre4j_InputReader_KC_F9
#define org_ogre4j_InputReader_KC_F9 67L
#undef org_ogre4j_InputReader_KC_F10
#define org_ogre4j_InputReader_KC_F10 68L
#undef org_ogre4j_InputReader_KC_NUMLOCK
#define org_ogre4j_InputReader_KC_NUMLOCK 69L
#undef org_ogre4j_InputReader_KC_SCROLL
#define org_ogre4j_InputReader_KC_SCROLL 70L
#undef org_ogre4j_InputReader_KC_NUMPAD7
#define org_ogre4j_InputReader_KC_NUMPAD7 71L
#undef org_ogre4j_InputReader_KC_NUMPAD8
#define org_ogre4j_InputReader_KC_NUMPAD8 72L
#undef org_ogre4j_InputReader_KC_NUMPAD9
#define org_ogre4j_InputReader_KC_NUMPAD9 73L
#undef org_ogre4j_InputReader_KC_SUBTRACT
#define org_ogre4j_InputReader_KC_SUBTRACT 74L
#undef org_ogre4j_InputReader_KC_NUMPAD4
#define org_ogre4j_InputReader_KC_NUMPAD4 75L
#undef org_ogre4j_InputReader_KC_NUMPAD5
#define org_ogre4j_InputReader_KC_NUMPAD5 76L
#undef org_ogre4j_InputReader_KC_NUMPAD6
#define org_ogre4j_InputReader_KC_NUMPAD6 77L
#undef org_ogre4j_InputReader_KC_ADD
#define org_ogre4j_InputReader_KC_ADD 78L
#undef org_ogre4j_InputReader_KC_NUMPAD1
#define org_ogre4j_InputReader_KC_NUMPAD1 79L
#undef org_ogre4j_InputReader_KC_NUMPAD2
#define org_ogre4j_InputReader_KC_NUMPAD2 80L
#undef org_ogre4j_InputReader_KC_NUMPAD3
#define org_ogre4j_InputReader_KC_NUMPAD3 81L
#undef org_ogre4j_InputReader_KC_NUMPAD0
#define org_ogre4j_InputReader_KC_NUMPAD0 82L
#undef org_ogre4j_InputReader_KC_DECIMAL
#define org_ogre4j_InputReader_KC_DECIMAL 83L
#undef org_ogre4j_InputReader_KC_OEM_102
#define org_ogre4j_InputReader_KC_OEM_102 86L
#undef org_ogre4j_InputReader_KC_F11
#define org_ogre4j_InputReader_KC_F11 87L
#undef org_ogre4j_InputReader_KC_F12
#define org_ogre4j_InputReader_KC_F12 88L
#undef org_ogre4j_InputReader_KC_F13
#define org_ogre4j_InputReader_KC_F13 100L
#undef org_ogre4j_InputReader_KC_F14
#define org_ogre4j_InputReader_KC_F14 101L
#undef org_ogre4j_InputReader_KC_F15
#define org_ogre4j_InputReader_KC_F15 102L
#undef org_ogre4j_InputReader_KC_KANA
#define org_ogre4j_InputReader_KC_KANA 112L
#undef org_ogre4j_InputReader_KC_ABNT_C1
#define org_ogre4j_InputReader_KC_ABNT_C1 115L
#undef org_ogre4j_InputReader_KC_CONVERT
#define org_ogre4j_InputReader_KC_CONVERT 121L
#undef org_ogre4j_InputReader_KC_NOCONVERT
#define org_ogre4j_InputReader_KC_NOCONVERT 123L
#undef org_ogre4j_InputReader_KC_YEN
#define org_ogre4j_InputReader_KC_YEN 125L
#undef org_ogre4j_InputReader_KC_ABNT_C2
#define org_ogre4j_InputReader_KC_ABNT_C2 126L
#undef org_ogre4j_InputReader_KC_NUMPADEQUALS
#define org_ogre4j_InputReader_KC_NUMPADEQUALS 141L
#undef org_ogre4j_InputReader_KC_PREVTRACK
#define org_ogre4j_InputReader_KC_PREVTRACK 144L
#undef org_ogre4j_InputReader_KC_AT
#define org_ogre4j_InputReader_KC_AT 145L
#undef org_ogre4j_InputReader_KC_COLON
#define org_ogre4j_InputReader_KC_COLON 146L
#undef org_ogre4j_InputReader_KC_UNDERLINE
#define org_ogre4j_InputReader_KC_UNDERLINE 147L
#undef org_ogre4j_InputReader_KC_KANJI
#define org_ogre4j_InputReader_KC_KANJI 148L
#undef org_ogre4j_InputReader_KC_STOP
#define org_ogre4j_InputReader_KC_STOP 149L
#undef org_ogre4j_InputReader_KC_AX
#define org_ogre4j_InputReader_KC_AX 150L
#undef org_ogre4j_InputReader_KC_UNLABELED
#define org_ogre4j_InputReader_KC_UNLABELED 151L
#undef org_ogre4j_InputReader_KC_NEXTTRACK
#define org_ogre4j_InputReader_KC_NEXTTRACK 153L
#undef org_ogre4j_InputReader_KC_NUMPADENTER
#define org_ogre4j_InputReader_KC_NUMPADENTER 156L
#undef org_ogre4j_InputReader_KC_RCONTROL
#define org_ogre4j_InputReader_KC_RCONTROL 157L
#undef org_ogre4j_InputReader_KC_MUTE
#define org_ogre4j_InputReader_KC_MUTE 160L
#undef org_ogre4j_InputReader_KC_CALCULATOR
#define org_ogre4j_InputReader_KC_CALCULATOR 161L
#undef org_ogre4j_InputReader_KC_PLAYPAUSE
#define org_ogre4j_InputReader_KC_PLAYPAUSE 162L
#undef org_ogre4j_InputReader_KC_MEDIASTOP
#define org_ogre4j_InputReader_KC_MEDIASTOP 164L
#undef org_ogre4j_InputReader_KC_VOLUMEDOWN
#define org_ogre4j_InputReader_KC_VOLUMEDOWN 174L
#undef org_ogre4j_InputReader_KC_VOLUMEUP
#define org_ogre4j_InputReader_KC_VOLUMEUP 176L
#undef org_ogre4j_InputReader_KC_WEBHOME
#define org_ogre4j_InputReader_KC_WEBHOME 178L
#undef org_ogre4j_InputReader_KC_NUMPADCOMMA
#define org_ogre4j_InputReader_KC_NUMPADCOMMA 179L
#undef org_ogre4j_InputReader_KC_DIVIDE
#define org_ogre4j_InputReader_KC_DIVIDE 181L
#undef org_ogre4j_InputReader_KC_SYSRQ
#define org_ogre4j_InputReader_KC_SYSRQ 183L
#undef org_ogre4j_InputReader_KC_RMENU
#define org_ogre4j_InputReader_KC_RMENU 184L
#undef org_ogre4j_InputReader_KC_PAUSE
#define org_ogre4j_InputReader_KC_PAUSE 197L
#undef org_ogre4j_InputReader_KC_HOME
#define org_ogre4j_InputReader_KC_HOME 199L
#undef org_ogre4j_InputReader_KC_UP
#define org_ogre4j_InputReader_KC_UP 200L
#undef org_ogre4j_InputReader_KC_PGUP
#define org_ogre4j_InputReader_KC_PGUP 201L
#undef org_ogre4j_InputReader_KC_LEFT
#define org_ogre4j_InputReader_KC_LEFT 203L
#undef org_ogre4j_InputReader_KC_RIGHT
#define org_ogre4j_InputReader_KC_RIGHT 205L
#undef org_ogre4j_InputReader_KC_END
#define org_ogre4j_InputReader_KC_END 207L
#undef org_ogre4j_InputReader_KC_DOWN
#define org_ogre4j_InputReader_KC_DOWN 208L
#undef org_ogre4j_InputReader_KC_PGDOWN
#define org_ogre4j_InputReader_KC_PGDOWN 209L
#undef org_ogre4j_InputReader_KC_INSERT
#define org_ogre4j_InputReader_KC_INSERT 210L
#undef org_ogre4j_InputReader_KC_DELETE
#define org_ogre4j_InputReader_KC_DELETE 211L
#undef org_ogre4j_InputReader_KC_LWIN
#define org_ogre4j_InputReader_KC_LWIN 219L
#undef org_ogre4j_InputReader_KC_RWIN
#define org_ogre4j_InputReader_KC_RWIN 220L
#undef org_ogre4j_InputReader_KC_APPS
#define org_ogre4j_InputReader_KC_APPS 221L
#undef org_ogre4j_InputReader_KC_POWER
#define org_ogre4j_InputReader_KC_POWER 222L
#undef org_ogre4j_InputReader_KC_SLEEP
#define org_ogre4j_InputReader_KC_SLEEP 223L
#undef org_ogre4j_InputReader_KC_WAKE
#define org_ogre4j_InputReader_KC_WAKE 227L
#undef org_ogre4j_InputReader_KC_WEBSEARCH
#define org_ogre4j_InputReader_KC_WEBSEARCH 229L
#undef org_ogre4j_InputReader_KC_WEBFAVORITES
#define org_ogre4j_InputReader_KC_WEBFAVORITES 230L
#undef org_ogre4j_InputReader_KC_WEBREFRESH
#define org_ogre4j_InputReader_KC_WEBREFRESH 231L
#undef org_ogre4j_InputReader_KC_WEBSTOP
#define org_ogre4j_InputReader_KC_WEBSTOP 232L
#undef org_ogre4j_InputReader_KC_WEBFORWARD
#define org_ogre4j_InputReader_KC_WEBFORWARD 233L
#undef org_ogre4j_InputReader_KC_WEBBACK
#define org_ogre4j_InputReader_KC_WEBBACK 234L
#undef org_ogre4j_InputReader_KC_MYCOMPUTER
#define org_ogre4j_InputReader_KC_MYCOMPUTER 235L
#undef org_ogre4j_InputReader_KC_MAIL
#define org_ogre4j_InputReader_KC_MAIL 236L
#undef org_ogre4j_InputReader_KC_MEDIASELECT
#define org_ogre4j_InputReader_KC_MEDIASELECT 237L
/*
 * Class:     org_ogre4j_InputReader
 * Method:    addCursorMoveListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_InputReader_addCursorMoveListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    capture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_InputReader_capture
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseAbsX
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseAbsX
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseAbsY
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseAbsY
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseAbsZ
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseAbsZ
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseButton
 * Signature: (IC)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_InputReader_getMouseButton
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseRelativeX
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseRelativeX
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseRelativeY
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseRelativeY
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseRelativeZ
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseRelativeZ
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseRelX
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseRelX
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseRelY
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseRelY
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    getMouseRelZ
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_InputReader_getMouseRelZ
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    initialise
 * Signature: (IIZZZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_InputReader_initialise
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    isKeyDown
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_InputReader_isKeyDown
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    removeCursorMoveListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_InputReader_removeCursorMoveListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_InputReader
 * Method:    setBufferedInput
 * Signature: (IZZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_InputReader_setBufferedInput
  (JNIEnv *, jclass, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
