/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_ShadowRenderable */

#ifndef _Included_org_ogre4j_ShadowRenderable
#define _Included_org_ogre4j_ShadowRenderable
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
#ifdef __cplusplus
}
#endif
#endif
