/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_RenderTarget */

#ifndef _Included_org_ogre4j_RenderTarget
#define _Included_org_ogre4j_RenderTarget
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    addListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_addListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    addViewport
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_RenderTarget_addViewport__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    addViewport
 * Signature: (IIIFFFF)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_RenderTarget_addViewport__IIIFFFF
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getAverageFPS
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_RenderTarget_getAverageFPS
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getBestFPS
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_RenderTarget_getBestFPS
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getBestFrameTime
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_RenderTarget_getBestFrameTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getColourDepth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_RenderTarget_getColourDepth
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getDebugText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_RenderTarget_getDebugText
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_RenderTarget_getHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getLastFPS
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_RenderTarget_getLastFPS
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_RenderTarget_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getNumViewports
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_RenderTarget_getNumViewports
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getPriority
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_org_ogre4j_RenderTarget_getPriority
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getTriangleCount
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogre4j_RenderTarget_getTriangleCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_RenderTarget_getWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getWorstFPS
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_RenderTarget_getWorstFPS
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    getWorstFrameTime
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_RenderTarget_getWorstFrameTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    isActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_RenderTarget_isActive
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    isAutoUpdated
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_RenderTarget_isAutoUpdated
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    isPrimary
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_RenderTarget_isPrimary
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    removeAllListeners
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_removeAllListeners
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    removeAllViewports
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_removeAllViewports
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    removeListener
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_removeListener
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    removeViewport
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_removeViewport
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    requiresTextureFlipping
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ogre4j_RenderTarget_requiresTextureFlipping
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    resetStatistics
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_resetStatistics
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    setActive
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_setActive
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    setAutoUpdated
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_setAutoUpdated
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    setDebugText
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_setDebugText
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    setPriority
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_setPriority
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     org_ogre4j_RenderTarget
 * Method:    update
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_RenderTarget_update
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
