/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_MaterialManager */

#ifndef _Included_org_ogre4j_MaterialManager
#define _Included_org_ogre4j_MaterialManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_MaterialManager
 * Method:    getSingletonImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_MaterialManager_getSingletonImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_MaterialManager
 * Method:    setDefaultAnisotropy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MaterialManager_setDefaultAnisotropy
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_MaterialManager
 * Method:    setDefaultTextureFiltering
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_MaterialManager_setDefaultTextureFiltering
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
