/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_EventTargetImpl */

#ifndef _Included_org_ogre4j_EventTargetImpl
#define _Included_org_ogre4j_EventTargetImpl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_EventTargetImpl
 * Method:    hook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_EventTargetImpl_hook
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
