/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_ResourceGroupManager */

#ifndef _Included_org_ogre4j_ResourceGroupManager
#define _Included_org_ogre4j_ResourceGroupManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    addResourceLocation
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_addResourceLocation
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jboolean);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    clearResourceGroup
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_clearResourceGroup
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    createResourceGroup
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_createResourceGroup
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    destroyResourceGroup
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_destroyResourceGroup
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    getSingletonImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_ResourceGroupManager_getSingletonImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    initialiseAllResourceGroups
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_initialiseAllResourceGroups
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    initialiseResourceGroup
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_initialiseResourceGroup
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    loadResourceGroup
 * Signature: (ILjava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_loadResourceGroup
  (JNIEnv *, jclass, jint, jstring, jboolean, jboolean);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    removeResourceLocation
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_removeResourceLocation
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    shutdownAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_shutdownAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_ResourceGroupManager
 * Method:    unloadResourceGroup
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_ResourceGroupManager_unloadResourceGroup
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
