/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Skeleton */

#ifndef _Included_org_ogre4j_Skeleton
#define _Included_org_ogre4j_Skeleton
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
#undef org_ogre4j_Skeleton_TS_LOCAL
#define org_ogre4j_Skeleton_TS_LOCAL 0L
#undef org_ogre4j_Skeleton_TS_PARENT
#define org_ogre4j_Skeleton_TS_PARENT 1L
#undef org_ogre4j_Skeleton_TS_WORLD
#define org_ogre4j_Skeleton_TS_WORLD 2L
/*
 * Class:     org_ogre4j_Skeleton
 * Method:    _createBone
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton__1createBone__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    _createBone
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton__1createBone__IS
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    _createBone
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton__1createBone__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    _createBone
 * Signature: (ILjava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton__1createBone__ILjava_lang_String_2S
  (JNIEnv *, jclass, jint, jstring, jshort);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    _updateTransforms
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Skeleton__1updateTransforms
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    createAnimation
 * Signature: (ILjava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_createAnimation
  (JNIEnv *, jclass, jint, jstring, jfloat);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Skeleton_dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getAnimation
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_getAnimation__IS
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getAnimation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_getAnimation__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getBlendMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_getBlendMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getBone
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_getBone__IS
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getBone
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_getBone__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_Skeleton_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getNumAnimations
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_ogre4j_Skeleton_getNumAnimations
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getNumBones
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_ogre4j_Skeleton_getNumBones
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    getRootBone
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Skeleton_getRootBone
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    removeAnimation
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Skeleton_removeAnimation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Skeleton_reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    setBindingPose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Skeleton_setBindingPose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Skeleton
 * Method:    setBlendMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Skeleton_setBlendMode
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
