/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_BillboardSet */

#ifndef _Included_org_ogre4j_BillboardSet
#define _Included_org_ogre4j_BillboardSet
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_BillboardSet
 * Method:    createBillboard
 * Signature: (IFFF)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_BillboardSet_createBillboard
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_BillboardSet
 * Method:    setDefaultWidth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_BillboardSet_setDefaultWidth
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_ogre4j_BillboardSet
 * Method:    setMaterialName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_BillboardSet_setMaterialName
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
