/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_SkeletonManager */

#ifndef _Included_org_ogre4j_SkeletonManager
#define _Included_org_ogre4j_SkeletonManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_SkeletonManager
 * Method:    _create
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZII)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_SkeletonManager__1create
  (JNIEnv *, jclass, jstring, jstring, jboolean, jint, jint);

/*
 * Class:     org_ogre4j_SkeletonManager
 * Method:    _getByName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_SkeletonManager__1getByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_ogre4j_SkeletonManager
 * Method:    _removeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_SkeletonManager__1removeAll
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_SkeletonManager
 * Method:    createCppInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_SkeletonManager_createCppInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_SkeletonManager
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_SkeletonManager_dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_SkeletonManager
 * Method:    getSingleton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_SkeletonManager_getSingleton
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
