/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Frustum */

#ifndef _Included_org_ogre4j_Frustum
#define _Included_org_ogre4j_Frustum
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
#undef org_ogre4j_Frustum_FRUSTUM_PLANE_BOTTOM
#define org_ogre4j_Frustum_FRUSTUM_PLANE_BOTTOM 5L
#undef org_ogre4j_Frustum_FRUSTUM_PLANE_FAR
#define org_ogre4j_Frustum_FRUSTUM_PLANE_FAR 1L
#undef org_ogre4j_Frustum_FRUSTUM_PLANE_LEFT
#define org_ogre4j_Frustum_FRUSTUM_PLANE_LEFT 2L
#undef org_ogre4j_Frustum_FRUSTUM_PLANE_NEAR
#define org_ogre4j_Frustum_FRUSTUM_PLANE_NEAR 0L
#undef org_ogre4j_Frustum_FRUSTUM_PLANE_RIGHT
#define org_ogre4j_Frustum_FRUSTUM_PLANE_RIGHT 3L
#undef org_ogre4j_Frustum_FRUSTUM_PLANE_TOP
#define org_ogre4j_Frustum_FRUSTUM_PLANE_TOP 4L
/*
 * Class:     org_ogre4j_Frustum
 * Method:    getFarClipDistance
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_Frustum_getFarClipDistance
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Frustum
 * Method:    getFOVy
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_Frustum_getFOVy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Frustum
 * Method:    getNearClipDistance
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_ogre4j_Frustum_getNearClipDistance
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Frustum
 * Method:    setAspectRatio
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Frustum_setAspectRatio
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_ogre4j_Frustum
 * Method:    setFarClipDistance
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Frustum_setFarClipDistance
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_ogre4j_Frustum
 * Method:    setFOVy
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Frustum_setFOVy
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_ogre4j_Frustum
 * Method:    setNearClipDistance
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Frustum_setNearClipDistance
  (JNIEnv *, jclass, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
