/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_PlatformManager */

#ifndef _Included_org_ogre4j_PlatformManager
#define _Included_org_ogre4j_PlatformManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_PlatformManager
 * Method:    createInputReader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_PlatformManager_createInputReader
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_PlatformManager
 * Method:    getSingletonImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_PlatformManager_getSingletonImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
