/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Camera */

#ifndef _Included_org_ogre4j_Camera
#define _Included_org_ogre4j_Camera
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
#undef org_ogre4j_Camera_FRUSTUM_PLANE_BOTTOM
#define org_ogre4j_Camera_FRUSTUM_PLANE_BOTTOM 5L
#undef org_ogre4j_Camera_FRUSTUM_PLANE_FAR
#define org_ogre4j_Camera_FRUSTUM_PLANE_FAR 1L
#undef org_ogre4j_Camera_FRUSTUM_PLANE_LEFT
#define org_ogre4j_Camera_FRUSTUM_PLANE_LEFT 2L
#undef org_ogre4j_Camera_FRUSTUM_PLANE_NEAR
#define org_ogre4j_Camera_FRUSTUM_PLANE_NEAR 0L
#undef org_ogre4j_Camera_FRUSTUM_PLANE_RIGHT
#define org_ogre4j_Camera_FRUSTUM_PLANE_RIGHT 3L
#undef org_ogre4j_Camera_FRUSTUM_PLANE_TOP
#define org_ogre4j_Camera_FRUSTUM_PLANE_TOP 4L
/*
 * Class:     org_ogre4j_Camera
 * Method:    getCameraToViewportRay
 * Signature: (IFF)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Camera_getCameraToViewportRay
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    getDerivedOrientation
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_ogre4j_Camera_getDerivedOrientation
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    getDerivedPosition
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_ogre4j_Camera_getDerivedPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    getDetailLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Camera_getDetailLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    getDirection
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_ogre4j_Camera_getDirection
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    getOrientation
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_ogre4j_Camera_getOrientation
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    getPosition
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_ogre4j_Camera_getPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    lookAt
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_lookAt
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    moveRelative
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_moveRelative
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    pitch
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_pitch
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    roll
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_roll
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setAutoTracking
 * Signature: (IZIFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setAutoTracking
  (JNIEnv *, jclass, jint, jboolean, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setDetailLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setDetailLevel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setDirection
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setDirection
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setFixedYawAxis
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setFixedYawAxis__IZ
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setFixedYawAxis
 * Signature: (IZFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setFixedYawAxis__IZFFF
  (JNIEnv *, jclass, jint, jboolean, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setOrientation
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setOrientation
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    setPosition
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_setPosition
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_ogre4j_Camera
 * Method:    yaw
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Camera_yaw
  (JNIEnv *, jclass, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
