/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_D3D7RenderSystem */

#ifndef _Included_org_ogre4j_D3D7RenderSystem
#define _Included_org_ogre4j_D3D7RenderSystem
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_D3D7RenderSystem
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_D3D7RenderSystem_getName
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
