/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_InstancePointer */

#ifndef _Included_org_ogre4j_InstancePointer
#define _Included_org_ogre4j_InstancePointer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
