/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Ray */

#ifndef _Included_org_ogre4j_Ray
#define _Included_org_ogre4j_Ray
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_Ray
 * Method:    createInstance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Ray_createInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_ogre4j_Ray
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Ray_dispose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
