/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogre4j_Overlay */

#ifndef _Included_org_ogre4j_Overlay
#define _Included_org_ogre4j_Overlay
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: table */
/*
 * Class:     org_ogre4j_Overlay
 * Method:    getChild
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ogre4j_Overlay_getChild
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_ogre4j_Overlay
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ogre4j_Overlay_getName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Overlay
 * Method:    getZOrder
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_ogre4j_Overlay_getZOrder
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Overlay
 * Method:    hide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Overlay_hide
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogre4j_Overlay
 * Method:    setZOrder
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Overlay_setZOrder
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_ogre4j_Overlay
 * Method:    show
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ogre4j_Overlay_show
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
