JAVAROOT = ../../../..

JAVASOURCES = \
	ColorManager.java \
	VarColorManager.java \
	ConstraintColorManager.java \
	EventColorManager.java \
	JVariableManager.java \
	JTreemap.java \
	JTimeControls.java \
	JLabelingManager.java \
	TickBar.java \
	DefaultTickBar.java \
	JTickBars.java \
	JConstraintManager.java \
	JHistoryViewer.java \
	JAdjacencyMatrix.java \
	JWeightedConstraintAdjacencyMatrix.java \
	JConstraintAdjacencyMatrix.java

all: java-classes.stamp 

include $(JAVAROOT)/Makefile.rules

