JAVAROOT = ../../..
SUBDIRS = event table tree graph helpers widgets

JAVASOURCES = \
	AbstractSolver.java \
	CommonAttributes.java \
	ConstraintAttributes.java \
	DefaultExplanation.java \
	DefaultMisc.java \
	DefaultMiscList.java \
	DefaultState.java \
	DefaultUpdate.java \
	DefaultUpdateList.java \
	DefaultValueList.java \
	DefaultVarDomain.java \
	DefaultVarDomainList.java \
	EventAttributes.java \
	Explanation.java \
	Misc.java \
	MiscList.java \
	SAXSolver.java \
	Solver.java \
	SolverConstants.java \
	StageAttributes.java \
	State.java \
	Update.java \
	UpdateList.java \
	ValueList.java \
	VarDomain.java \
	VarDomainList.java \
	Variable.java \
	VariableManager.java \
	LabelingManager.java \
	Constraint.java \
	ConstraintManager.java \
	HistoryManager.java \
	DefaultIdentifiable.java

all: subdirs java-classes.stamp 

include $(JAVAROOT)/Makefile.rules

