/*******************************************************************************
 * Copyright (c) 2001-2014 Yann-Gaël Guéhéneuc and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     Yann-Gaël Guéhéneuc and others, see in file; API and its implementation
 ******************************************************************************/
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 23 18:05:49 EDT 2007
//----------------------------------------------------

package sad.rule.creator;

/** CUP generated interface containing symbol constants. */
public interface RULESymbols {
	/* terminals */
	public static final int SUP_EQ = 54;
	public static final int IS_ABSTRACT = 30;
	public static final int GLOBAL_VARIABLE = 29;
	public static final int HIGH = 19;
	public static final int ASSOC = 38;
	public static final int LPAREN = 3;
	public static final int SEMI = 2;
	public static final int MINUS = 49;
	public static final int OPTIONNALY_ONE = 45;
	public static final int INCL = 11;
	public static final int RPAREN = 4;
	public static final int RULE = 47;
	public static final int METRIC = 15;
	public static final int VERY_HIGH = 18;
	public static final int INF = 50;
	public static final int SEMANTIC = 16;
	public static final int VERY_LOW = 22;
	public static final int CLASSNAME = 24;
	public static final int PLUS = 48;
	public static final int MULTIPLE_INTERFACE = 35;
	public static final int AGGREG = 39;
	public static final int EOF = 0;
	public static final int PUBLIC_FIELD = 34;
	public static final int LOW = 21;
	public static final int error = 1;
	public static final int DIFFERENT_PARAMETER = 31;
	public static final int EQ = 52;
	public static final int COMPOS = 40;
	public static final int FROM = 36;
	public static final int ONE = 42;
	public static final int MANY = 43;
	public static final int NONE = 23;
	public static final int COLON = 7;
	public static final int INF_EQ = 51;
	public static final int UNION = 9;
	public static final int NEG = 12;
	public static final int LBRACE = 5;
	public static final int ONE_OR_MANY = 44;
	public static final int NOT_EQ = 55;
	public static final int TO = 37;
	public static final int PRIVATE_FIELD = 33;
	public static final int MEDIUM = 20;
	public static final int ONE_METHOD = 32;
	public static final int METHOD_NO_PARAM = 28;
	public static final int SUP = 53;
	public static final int RBRACE = 6;
	public static final int INHERIT = 41;
	public static final int DIFF = 10;
	public static final int RULE_CARD = 46;
	public static final int METHODNAME = 25;
	public static final int STRUCT = 17;
	public static final int INTER = 8;
	public static final int TWO_DOT = 14;
	public static final int FIELDNAME = 26;
	public static final int METHOD_ACCESSOR = 27;
	public static final int IDENTIFIER = 13;

	/* non terminals */
	static final int string = 22;
	static final int relationship = 19;
	static final int list_rules = 3;
	static final int cardinality = 21;
	static final int value_semantic = 14;
	static final int rule = 4;
	static final int operator = 6;
	static final int $START = 0;
	static final int name_relation = 20;
	static final int id_metric = 9;
	static final int comparison_operator = 11;
	static final int attribute = 8;
	static final int list_attributes = 7;
	static final int cont_value_semantic = 15;
	static final int id_semantic = 13;
	static final int id_struct_noparam = 17;
	static final int content_rule = 5;
	static final int value_ordi = 10;
	static final int list_relationships = 18;
	static final int set_rules = 1;
	static final int rule_card = 2;
	static final int fuzziness = 12;
	static final int id_struct_param = 16;
}
