/*******************************************************************************
 * Copyright (c) 2001-2014 Yann-Gaël Guéhéneuc and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     Yann-Gaël Guéhéneuc and others, see in file; API and its implementation
 ******************************************************************************/
package sad.designsmell.detection.repository.BaseClassShouldBeAbstract;

/**
 * This class implements the detection algorithms 
 * of the design smell BaseClassShouldBeAbstract.
 * 
 * @author Autogenerated files
 * 
 */

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import padl.kernel.IAbstractLevelModel;
import sad.codesmell.detection.repository.BaseClassShouldBeAbstract.*;
import sad.kernel.ICodeSmell;
import sad.codesmell.detection.ICodeSmellDetection;
import sad.designsmell.detection.IDesignSmellDetection;
import sad.designsmell.detection.repository.AbstractDesignSmellDetection;
import sad.kernel.impl.DesignSmell;
import sad.util.OperatorsCodeSmells;
import sad.util.Relationships;

public class BaseClassShouldBeAbstractDetection extends AbstractDesignSmellDetection implements IDesignSmellDetection {
	private final OperatorsCodeSmells operators;
	private final Relationships relations;

	public BaseClassShouldBeAbstractDetection() {
		super();

		this.operators = OperatorsCodeSmells.getInstance();
		this.relations = Relationships.getInstance();
	}
	
	public String getName() {
		return "BaseClassShouldBeAbstract";
	}

	public String getRuleCardFile() {
		return "../SAD Rules Creator/rsc/BaseClassShouldBeAbstract.rules";
	}

	
public void detect(final IAbstractLevelModel anAbstractLevelModel) {
final Set candidateDesignSmells = new HashSet();

final ICodeSmellDetection csHasChildren = new HasChildrenDetection();
csHasChildren.detect(anAbstractLevelModel);
final Set setHasChildren = ((HasChildrenDetection) csHasChildren).getCodeSmells();

final ICodeSmellDetection csNoInheritance = new NoInheritanceDetection();
csNoInheritance.detect(anAbstractLevelModel);
final Set setNoInheritance = ((NoInheritanceDetection) csNoInheritance).getCodeSmells();

final Set setBaseClass = 
this.operators.intersection(setNoInheritance,setHasChildren);

final ICodeSmellDetection csNotAbstract = new NotAbstractDetection();
csNotAbstract.detect(anAbstractLevelModel);
final Set setNotAbstract = ((NotAbstractDetection) csNotAbstract).getCodeSmells();

final Set setBaseClassShouldBeAbstract = 
this.operators.intersection(setBaseClass,setNotAbstract);

final Iterator iterSet = setBaseClassShouldBeAbstract.iterator();
while(iterSet.hasNext()) {
final ICodeSmell aCodeSmell = (ICodeSmell) iterSet.next();
final DesignSmell designSmell = new DesignSmell(aCodeSmell);
designSmell.setName("BaseClassShouldBeAbstract");
final String definition = "To defined";
designSmell.setDefinition(definition);
candidateDesignSmells.add(designSmell);
}
this.setSetOfDesignSmells(candidateDesignSmells);
}
}
