/*******************************************************************************
 * Copyright (c) 2001-2014 Yann-Gaël Guéhéneuc and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * 
 * Contributors:
 *     Yann-Gaël Guéhéneuc and others, see in file; API and its implementation
 ******************************************************************************/
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 11 22:19:51 EDT 2011
//----------------------------------------------------

package padl.creator.aolfile.parser;

/** CUP generated interface containing symbol constants. */
public interface AOLSymbols {
  /* terminals */
  public static final int PARTS = 21;
  public static final int CONTAINER = 9;
  public static final int MULT = 15;
  public static final int CONST = 7;
  public static final int SHARED = 31;
  public static final int TEMPLATE = 33;
  public static final int OPERATIONS = 19;
  public static final int LPAREN = 13;
  public static final int PRIVATE = 23;
  public static final int GENERALIZATION = 10;
  public static final int AGGREGATION = 3;
  public static final int OPTIONALLY_ONE = 20;
  public static final int RPAREN = 29;
  public static final int SUBCLASSES = 32;
  public static final int SEMICOLON = 30;
  public static final int COMMA = 8;
  public static final int CLASS = 5;
  public static final int ATTRIBUTES = 4;
  public static final int RELATION = 27;
  public static final int ABSTRACT = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int UNSIGNED = 37;
  public static final int UNDEFINED = 36;
  public static final int NAME = 16;
  public static final int ONE = 17;
  public static final int UNDEF_SCOPE = 35;
  public static final int COLON = 6;
  public static final int MANY = 14;
  public static final int LBRACE = 12;
  public static final int PROTECTED = 24;
  public static final int ONE_OR_MANY = 18;
  public static final int PUBLIC = 25;
  public static final int ROLES = 28;
  public static final int RBRACE = 26;
  public static final int TYPENAME = 34;
  public static final int VOLATILE = 38;
  public static final int POINTER = 22;
  public static final int IDENTIFIER = 11;

  /* non terminals */
  static final int string = 28;
  static final int multiplicity = 23;
  static final int declaration = 3;
  static final int template_return_type = 18;
  static final int generalization = 25;
  static final int association_arg = 20;
  static final int operation_content = 13;
  static final int list_declarations = 2;
  static final int association = 19;
  static final int model = 1;
  static final int fully_qualified_name = 27;
  static final int class_declaration = 4;
  static final int class_content = 5;
  static final int $START = 0;
  static final int operation = 10;
  static final int operation_list = 9;
  static final int attribute = 7;
  static final int roles = 21;
  static final int sub_classes_names = 26;
  static final int aggregation = 24;
  static final int operation_name = 12;
  static final int operation_arg = 15;
  static final int attribute_type_list = 8;
  static final int visibility = 11;
  static final int operation_arg_list = 14;
  static final int attribute_list = 6;
  static final int operation_type_list = 16;
  static final int template_content = 17;
  static final int role = 22;
}

