JAVAROOT = ../../../..

JAVASOURCES = \
	Node.java \
	Weight.java \
	Tree.java \
	NodeEnumeration.java \
	TreeVisitor.java \
	SumWeightVisitor.java \
	AttributeVector.java \
	AttributedTree.java \
	AttributedTreePrinter.java \
	IntAttributeVector.java \
	FloatAttributeVector.java \
	StringAttributeVector.java \
	TreeDirLoader.java \
	Box.java \
	Drawer.java \
	Treemap.java \
	Direction.java \
	SliceAndDice.java \
	BorderDrawer.java \
	ColorDrawer.java \
	GraphicsDrawer.java

all: java-classes.stamp 

include $(JAVAROOT)/Makefile.rules
