cluster --exe ./CallDesignMotifIdentification.sh 7 0 &
cluster --exe ./CallDesignMotifIdentification.sh 7 1 &
cluster --exe ./CallDesignMotifIdentification.sh 7 2 &
cluster --exe ./CallDesignMotifIdentification.sh 7 3 &
cluster --exe ./CallDesignMotifIdentification.sh 7 4 &
cluster --exe ./CallDesignMotifIdentification.sh 7 5 &
cluster --exe ./CallDesignMotifIdentification.sh 7 6 &
cluster --exe ./CallDesignMotifIdentification.sh 7 7 &
cluster --exe ./CallDesignMotifIdentification.sh 7 9 &
