cluster --exe ./CallDesignMotifIdentification.sh 2 0 &
cluster --exe ./CallDesignMotifIdentification.sh 2 1 &
cluster --exe ./CallDesignMotifIdentification.sh 2 2 &
cluster --exe ./CallDesignMotifIdentification.sh 2 3 &
cluster --exe ./CallDesignMotifIdentification.sh 2 4 &
cluster --exe ./CallDesignMotifIdentification.sh 2 5 &
cluster --exe ./CallDesignMotifIdentification.sh 2 6 &
cluster --exe ./CallDesignMotifIdentification.sh 2 7 &
cluster --exe ./CallDesignMotifIdentification.sh 2 8 &
