/*
 * $Id: ConstraintChangedEvent.java,v 1.1 2004/03/01 15:37:17 guehene Exp $
 *
 * Copyright (c) 2001-2002 Jean-Daniel Fekete, Mohammad Ghoniem and
 * Ecole des Mines de Nantes.  All rights reserved.
 *
 * This software is proprietary information of Jean-Daniel Fekete and
 * Ecole des Mines de Nantes.  You shall use it only in accordance
 * with the terms of the license agreement you accepted when
 * downloading this software.  The license is available in the file
 * licence.txt and at the following URL:
 * http://www.emn.fr/fekete/oadymppac/licence.html
 */
package fr.emn.oadymppac.event;

import fr.emn.oadymppac.Constraint;

/**
 * Event generated by a ConstraintManager when constraints are added
 * or removed.
 *
 * @author Jean-Daniel Fekete
 * @version $Revision: 1.1 $
 */

public class ConstraintChangedEvent extends BasicSolverEvent {
	public static final short ADDED = 0;
	public static final short REMOVED = 1;
	public static final short ACTIVATED = 2;
	public static final short DEACTIVATED = 3;

	Constraint constraint;
	short action;
	BasicSolverEvent event;

	public ConstraintChangedEvent() {
	}
	public ConstraintChangedEvent(
		final Constraint c,
		final short action,
		final BasicSolverEvent event) {
		super(event, false);
		this.constraint = c;
		this.action = action;
		this.event = event;
	}
	public ConstraintChangedEvent(
		final ConstraintChangedEvent other,
		final boolean deep) {
		super(other, deep);
		this.constraint = other.constraint;
		this.action = other.action;
		this.event = other.event;
	}

	public BasicSolverEvent deepClone() {
		return new ConstraintChangedEvent(this, true);
	}
	/**
	 * Get the value of action.
	 * @return value of action.
	 */
	public short getAction() {
		return this.action;
	}

	public Constraint getConstraint() {
		return this.constraint;
	}

	public BasicSolverEvent getEvent() {
		return this.event;
	}

	/**
	 * Set the value of action.
	 * @param v  Value to assign to action.
	 */
	public void setAction(final short v) {
		this.action = v;
	}

	public void setConstraint(final Constraint c) {
		this.constraint = c;
	}
	public void setEvent(final BasicSolverEvent event) {
		this.event = event;
	}
}
