
JAVAROOT = ../../../..

JAVASOURCES = \
	ActivateEvent.java \
	ActivateListener.java \
	BasicSolverEvent.java \
	DeactivateEvent.java \
	DeactivateListener.java \
	DomainChangedEvent.java \
	DomainChangedListener.java \
	EventAttributes.java \
	NewConstraintEvent.java \
	NewConstraintListener.java \
	NewStageEvent.java \
	NewVariableEvent.java \
	NewVariableListener.java \
	ReduceEvent.java \
	ReduceListener.java \
	RejectEvent.java \
	RejectListener.java \
	RestoreEvent.java \
	RestoreListener.java \
	SelectConstraintEvent.java \
	SelectConstraintListener.java \
	SelectUpdateEvent.java \
	SelectUpdateListener.java \
	SolutionEvent.java \
	SolutionListener.java \
	SolverEvent.java \
	StageEvent.java \
	StageListener.java \
	SuspendEvent.java \
	SuspendListener.java \
	TellEvent.java \
	TellListener.java \
	TrueEvent.java \
	TrueListener.java \
	WakeUpEvent.java \
	WakeUpListener.java \
	DomainChangedEvent.java \
	DomainChangedListener.java \
	LabeledVariableEvent.java \
	LabeledVariableListener.java \
	ConstraintChangedEvent.java \
	ConstraintChangedListener.java

all: java-classes.stamp 

include $(JAVAROOT)/Makefile.rules
