//
// Generated by JTB 1.2.2
//

package util.parser.java.v14.nodes;

/**
 * Grammar production:
 * f0 -> ConditionalAndExpression()
 * f1 -> ( "||" ConditionalAndExpression() )*
 */
public class ConditionalOrExpression implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public ConditionalAndExpression f0;
   public NodeListOptional f1;

   public ConditionalOrExpression(ConditionalAndExpression n0, NodeListOptional n1) {
      this.f0 = n0;
      this.f1 = n1;
   }

   public void accept(util.parser.java.v14.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v14.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

