//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "{"
 * f1 -> ( AnnotationTypeMemberDeclaration() )*
 * f2 -> "}"
 */
public class AnnotationTypeBody implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public NodeToken f0;
   public NodeListOptional f1;
   public NodeToken f2;

   public AnnotationTypeBody(NodeToken n0, NodeListOptional n1, NodeToken n2) {
      this.f0 = n0;
      this.f1 = n1;
      this.f2 = n2;
   }

   public AnnotationTypeBody(NodeListOptional n0) {
      this.f0 = new NodeToken("{");
      this.f1 = n0;
      this.f2 = new NodeToken("}");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

