//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "("
 * f1 -> [ ArgumentList() ]
 * f2 -> ")"
 */
public class Arguments implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public NodeToken f0;
   public NodeOptional f1;
   public NodeToken f2;

   public Arguments(NodeToken n0, NodeOptional n1, NodeToken n2) {
      this.f0 = n0;
      this.f1 = n1;
      this.f2 = n2;
   }

   public Arguments(NodeOptional n0) {
      this.f0 = new NodeToken("(");
      this.f1 = n0;
      this.f2 = new NodeToken(")");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

