//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> ( "class" | "interface" )
 * f1 -> <IDENTIFIER>
 * f2 -> [ TypeParameters() ]
 * f3 -> [ ExtendsList() ]
 * f4 -> [ ImplementsList() ]
 * f5 -> ClassOrInterfaceBody()
 */
public class ClassOrInterfaceDeclaration implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public NodeChoice f0;
   public NodeToken f1;
   public NodeOptional f2;
   public NodeOptional f3;
   public NodeOptional f4;
   public ClassOrInterfaceBody f5;

   public ClassOrInterfaceDeclaration(NodeChoice n0, NodeToken n1, NodeOptional n2, NodeOptional n3, NodeOptional n4, ClassOrInterfaceBody n5) {
      this.f0 = n0;
      this.f1 = n1;
      this.f2 = n2;
      this.f3 = n3;
      this.f4 = n4;
      this.f5 = n5;
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

