//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(util.parser.java.v15.visitors.Visitor v);
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu);

}

