//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
">"
 * f0 -> ">"
 */
public class RSIGNEDSHIFT implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public NodeToken f0;
   public NodeToken f1;

   public RSIGNEDSHIFT(NodeToken n0, NodeToken n1) {
      this.f0 = n0;
      this.f1 = n1;
   }

   public RSIGNEDSHIFT() {
      this.f0 = new NodeToken(">");
      this.f1 = new NodeToken(">");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

