//
// Generated by JTB 1.2.2
//

package util.parser.java.v15.nodes;

/**
 * Grammar production:
 * f0 -> "<"
 * f1 -> TypeArgument()
 * f2 -> ( "," TypeArgument() )*
 * f3 -> ">"
 */
public class TypeArguments implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public NodeToken f0;
   public TypeArgument f1;
   public NodeListOptional f2;
   public NodeToken f3;

   public TypeArguments(NodeToken n0, TypeArgument n1, NodeListOptional n2, NodeToken n3) {
      this.f0 = n0;
      this.f1 = n1;
      this.f2 = n2;
      this.f3 = n3;
   }

   public TypeArguments(TypeArgument n0, NodeListOptional n1) {
      this.f0 = new NodeToken("<");
      this.f1 = n0;
      this.f2 = n1;
      this.f3 = new NodeToken(">");
   }

   public void accept(util.parser.java.v15.visitors.Visitor v) {
      v.visit(this);
   }
   public Object accept(util.parser.java.v15.visitors.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

