JAVAROOT = ../../../..

JAVASOURCES = \
	VariableManagerCell.java \
	VariableManagerCellRenderer.java \
	VariableManagerTableModel.java

all: java-classes.stamp 

include $(JAVAROOT)/Makefile.rules

